volumes:
  postgres-data:
  redis_data:

services:
  postgres-referral:
    container_name: postgres-referral
    image: postgres:15
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
    networks:
      - referral_network

  redis-referral:
    container_name: redis-referral
    image: redis/redis-stack:6.2.6-v5
    env_file: .env
    volumes:
      - redis_data:/data
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - referral_network

networks:
  referral_network:
    name: referral_network
