"""Added Code table

Revision ID: 6f644a03356a
Revises: 523d1957f515
Create Date: 2025-02-24 10:53:39.517066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f644a03356a'
down_revision: Union[str, None] = '523d1957f515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code',
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('user_sid', sa.Uuid(), nullable=False),
    sa.Column('value', sa.String(), nullable=False, comment='value of referral code'),
    sa.Column('lifetime', sa.DateTime(), nullable=False, comment='Lifetime of referral code'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_sid'], ['users.user.sid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sid', 'user_sid'),
    sa.UniqueConstraint('sid'),
    schema='codes',
    comment='codes module schema'
    )
    op.create_index(op.f('ix_codes_code_value'), 'code', ['value'], unique=True, schema='codes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_codes_code_value'), table_name='code', schema='codes')
    op.drop_table('code', schema='codes')
    # ### end Alembic commands ###
