"""Added Invitation table

Revision ID: 7abc61ddd116
Revises: 6f644a03356a
Create Date: 2025-02-24 13:06:21.302350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7abc61ddd116'
down_revision: Union[str, None] = '6f644a03356a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation',
    sa.Column('referrer', sa.Uuid(), nullable=False),
    sa.Column('referral', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['referral'], ['users.user.sid'], ),
    sa.ForeignKeyConstraint(['referrer'], ['users.user.sid'], ),
    sa.PrimaryKeyConstraint('referrer', 'referral'),
    schema='users',
    comment='users module schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitation', schema='users')
    # ### end Alembic commands ###
